vagrantfile:
    target: local
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: vagrant1
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_xk3fp4vulr5s:
                    host: '6232'
                    guest: '22'
                vflnp_k694yoxwp2h7:
                    host: '8181'
                    guest: '443'
                vflnp_0limihmkeclz:
                    host: '8180'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vfawssf_ndd90ejme9je:
                source: ../web
                target: /var/www/ccdaa/web
                sync_type: default
                owner: www-data
                group: www-data
            vfawssf_o7l425thhnhu:
                source: ../api
                target: /var/www/ccdaa/api
                sync_type: default
                owner: www-data
                group: www-data
            vfawssf_n3d9j39djkd9:
                source: ../sql
                target: /sql
                sync_type: default
                owner: www-data
                group: www-data
            wjejf78409gjnr9fgifn:
                source: ../../ccdaa_media/
                target: /var/www/ccdaa/videos
                sync_type: default
                owner: www-data
                group: www-data
            vfawssf_dkf9056nd94n:
                source: certs/vagrant1
                target: /etc/apache2/ssl
                sync_type: default
                owner: root
                group: root
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'

mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_l0ux1btcldlz:
            name: ccdaa
            password: '123'
    databases:
        mysqlnd_qri5yd3zfa6w:
            name: ccdaa
            sql: /sql/ccdaa_all.sql
    grants:
        mysqlng_aggegor2u1yt:
            user: ccdaa
            table: '*.*'
            privileges:
                - ALL

apache:
    install: '1'
    vhosts:
        av_kx7shasytkep:
            directories:
                avd_3z3cy8nsg5yu:
                    path: /var/www/ccdaa/adminer
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_wvhpewzems28:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
daa:
    url: https://vagrant1/api/v1/
