--
-- Contents of 0.13.4/01_0.13.4_spanish_english_changes_and_updates.sql
--
-- Seccion Encuesta Inicial
UPDATE `preferences_text` SET `id` = '1267', `languages_id` = '2', `title` = 'Indios americanos y nativos de Alaska', `description` = 'american_indian_or_alaska_native', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '29' WHERE `id` = '1267';
UPDATE `preferences_text` SET `id` = '1263', `languages_id` = '2', `title` = 'Nativo de Hawaii u otras islas del Pacífico', `description` = 'native_hawaiian_or_other_pacific_islander', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '25' WHERE `id` = '1263';

-- Seccion A Fatalismo
UPDATE `preferences_text` SET `id` = '1337', `languages_id` = '2', `title` = 'Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon.', `description` = '', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '53', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`description` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`default` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%') AND `id` = '1337';
UPDATE `preferences_text` SET `id` = '4482', `languages_id` = '2', `title` = 'Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon.', `description` = '', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '423', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`description` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`default` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Pienso que si alguien va a tener cáncer de colon, no importa que coman alimentos sanos, ellos desarrollarán el cáncer del colon de%') AND `id` = '4482';

-- Seccion D Beneficios
UPDATE `preferences_text` SET `id` = '1466', `languages_id` = '2', `title` = 'Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta.', `description` = '', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '85', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`description` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`default` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%') AND `id` = '1466';
UPDATE `preferences_text` SET `id` = '1471', `languages_id` = '2', `title` = 'Creo que un examen que detecte el cáncer del colon temprano puede ayudarme a proteger mi salud.', `description` = '', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '86', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`description` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`default` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%') AND `id` = '1471';
UPDATE `preferences_text` SET `id` = '3483', `languages_id` = '2', `title` = 'Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta.', `description` = '', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '319', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`description` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`default` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%') AND `id` = '3483';
UPDATE `preferences_text` SET `id` = '3485', `languages_id` = '2', `title` = 'Creo que un examen que detecte el cáncer del colon temprano puede ayudarme a proteger mi salud.', `description` = '', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '320', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`description` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`default` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Son más los beneficios de tener una prueba médica para detectar el cáncer del colon temprano, que cualquier dificultad que pueda resultar de ésta%') AND `id` = '3485';

-- Seccion E
UPDATE `preferences_text` SET `id` = '1289', `languages_id` = '2', `title` = 'Percepción de Susceptibilidad', `description` = 'Sección E.', `instructions` = 'Las siguientes declaraciones son acerca de que tan probable es que usted tenga cáncer de colon  o que tanto le preocupa tener cáncer de colon. Favor de indicar cómo se siente sobre las siguientes declaraciones.', `placeholder` = 'Siguiente', `default` = 'Anterior', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '7', `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`description` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`default` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%') AND `id` = '1289';
UPDATE `preferences_text` SET `id` = '3271', `languages_id` = '2', `title` = 'Percepción de Susceptibilidad', `description` = 'Sección E.', `instructions` = 'Las siguientes declaraciones son acerca de que tan probable es que usted tenga cáncer de colon  o que tanto le preocupa tener cáncer de colon. Favor de indicar cómo se siente sobre las siguientes declaraciones.', `placeholder` = 'Siguiente', `default` = 'Anterior', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '62', `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`description` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`default` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Percepción de Suceptibilidad%') AND `id` = '3271';
UPDATE `preferences_text` SET `id` = '1502', `languages_id` = '2', `title` = 'Mucho', `description` = '4', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '208' WHERE `languages_id` = '2' AND (CONVERT(`title` USING utf8mb4) = 'Very' OR CONVERT(`description` USING utf8mb4) = 'Very' OR CONVERT(`instructions` USING utf8mb4) = 'Very' OR CONVERT(`placeholder` USING utf8mb4) = 'Very' OR CONVERT(`default` USING utf8mb4) = 'Very' OR CONVERT(`object_label` USING utf8mb4) = 'Very') AND `id` = '1502';
UPDATE `preferences_text` SET `id` = '1522', `languages_id` = '2', `title` = 'Mucho', `description` = '4', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '227' WHERE `languages_id` = '2' AND (CONVERT(`title` USING utf8mb4) = 'Very' OR CONVERT(`description` USING utf8mb4) = 'Very' OR CONVERT(`instructions` USING utf8mb4) = 'Very' OR CONVERT(`placeholder` USING utf8mb4) = 'Very' OR CONVERT(`default` USING utf8mb4) = 'Very' OR CONVERT(`object_label` USING utf8mb4) = 'Very') AND `id` = '1522';

-- Seccion E
UPDATE `preferences_text` SET `title` = 'Moderadamente' WHERE `title` = 'Moderadame';

-- Seccion G
UPDATE `preferences_text` SET `id` = '1595', `languages_id` = '2', `title` = 'Hacerme el examen de cáncer de colon, aunque tengo problemas de transporte.', `description` = '', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '109', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`description` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`default` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%') AND `id` = '1595';
UPDATE `preferences_text` SET `id` = '3673', `languages_id` = '2', `title` = 'Hacerme el examen de cáncer de colon, aunque tengo problemas de transporte.', `description` = '', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '343', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`description` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`default` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Hacerme el examen de cáncer de colon, aunque tengo problemas de transportación%') AND `id` = '3673';

-- Seccion J Aculturacion
UPDATE `preferences_text` SET `id` = '1657', `languages_id` = '2', `title` = 'La mayoría en Latinoamérica, específicamente en México', `description` = '2', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '359' WHERE `id` = '1657';
UPDATE `preferences_text` SET `id` = '1663', `languages_id` = '2', `title` = 'Casi exclusivamente Hispanos / Latinos', `description` = '1', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '364' WHERE `languages_id` = '2' AND `title` LIKE '%latin%' AND `id` = '1663';
UPDATE `preferences_text` SET `id` = '1664', `languages_id` = '2', `title` = 'La mayoría Hispanos / Latinos', `description` = '2', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '365' WHERE `id` = '1664';
UPDATE `preferences_text` SET `id` = '1665', `languages_id` = '2', `title` = 'Igualmente Hispanos / Latinos y Americanos no-Hispanos (Anglo Americanos, Africo Americanos, Asiáticos/ Islas del Pacifico, etc.)', `description` = '3', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '366' WHERE `answers_id` IN (366,367,368) AND `id` = '1665';
UPDATE `preferences_text` SET `id` = '1666', `languages_id` = '2', `title` = 'Mayormente Americanos no-Hispanos', `description` = '4', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '367' WHERE `answers_id` IN (366,367,368) AND `id` = '1666';
UPDATE `preferences_text` SET `id` = '1667', `languages_id` = '2', `title` = 'Casi exclusivamente Americanos no-Hispanos', `description` = '5', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '368' WHERE `answers_id` IN (366,367,368) AND `id` = '1667';

-- Section J Acculturation (were these even needed?)
UPDATE `preferences_text` SET `id` = '499', `languages_id` = '1', `title` = 'Equally Hispanics/Latinos and non-Hispanic Americans (Anglo Americans, African Americans, Asians/Pacific Islanders, etc.)', `description` = '3', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '366' WHERE `answers_id` IN (366,367,368) AND `id` = '499';
UPDATE `preferences_text` SET `id` = '500', `languages_id` = '1', `title` = 'Mainly non-Hispanic American', `description` = '4', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '367' WHERE `answers_id` IN (366,367,368) AND `id` = '500';
UPDATE `preferences_text` SET `id` = '501', `languages_id` = '1', `title` = 'Almost exclusively non-Hispanic American', `description` = '5', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '368' WHERE `answers_id` IN (366,367,368) AND `id` = '501';

-- SURE
UPDATE `preferences_text` SET `id` = '2521', `languages_id` = '2', `title` = 'SURE Test versión para la práctica clínica', `description` = '', `instructions` = '', `placeholder` = 'Terminado', `default` = 'Comenzar', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = '19', `sections_id` = NULL, `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`description` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`default` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%') AND `id` = '2521';
UPDATE `preferences_text` SET `id` = '2522', `languages_id` = '2', `title` = '', `description` = '', `instructions` = '', `placeholder` = 'Siguiente', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '46', `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`description` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`default` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%') AND `id` = '2522';
UPDATE `preferences_text` SET `id` = '3279', `languages_id` = '2', `title` = '', `description` = '', `instructions` = '', `placeholder` = 'Siguiente', `default` = 'Anterior', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '66', `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`description` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`default` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%SURE Test versión para la práctica clínica%') AND `id` = '3279';
UPDATE `preferences_text` SET `id` = '2952', `languages_id` = '2', `title` = '', `description` = '', `instructions` = '', `placeholder` = 'Siguiente', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '47', `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`description` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`default` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Alfabetización de la Salud%') AND `id` = '2952';
UPDATE `preferences_text` SET `id` = '2954', `languages_id` = '2', `title` = 'Alfabetización de la Salud', `description` = '', `instructions` = '', `placeholder` = 'Terminado', `default` = 'Comenzar', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = '20', `sections_id` = NULL, `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`description` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`default` USING utf8mb4) LIKE '%Alfabetización de la Salud%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Alfabetización de la Salud%') AND `id` = '2954';
UPDATE `preferences_text` SET `id` = '3057', `languages_id` = '2', `title` = 'Escala aritmética subjetiva', `description` = '', `instructions` = '', `placeholder` = 'Comenzar', `default` = 'Terminado', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = '21', `sections_id` = NULL, `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Subjetivo escala aritmética (SNS)%' OR CONVERT(`description` USING utf8mb4) LIKE '%Subjetivo escala aritmética (SNS)%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Subjetivo escala aritmética (SNS)%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Subjetivo escala aritmética (SNS)%' OR CONVERT(`default` USING utf8mb4) LIKE '%Subjetivo escala aritmética (SNS)%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Subjetivo escala aritmética (SNS)%') AND `id` = '3057';
UPDATE `preferences_text` SET `id` = '2520', `languages_id` = '2', `title` = 'Mi Decisión', `description` = 'Teniendo en cuenta la opción que prefiera, por favor conteste las siguientes preguntas:', `instructions` = '', `placeholder` = 'Siguiente', `default` = 'Anterior', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '45', `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Hecho%' OR CONVERT(`description` USING utf8mb4) LIKE '%Hecho%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Hecho%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Hecho%' OR CONVERT(`default` USING utf8mb4) LIKE '%Hecho%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Hecho%') AND `id` = '2520';
UPDATE `preferences_text` SET `id` = '3059', `languages_id` = '2', `title` = '', `description` = '', `instructions` = 'Para cada una de las siguientes preguntas, por favor marque la respuesta que refleje mejor qué tan bueno es usted para realizar las siguientes cosas:', `placeholder` = 'Siguiente', `default` = 'Anterior', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '57', `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Para cada una de las siguientes preguntas, por favor marque el cuadrito con la respuesta que refleje mejor qué tan bueno es usted para realizar las siguientes cosas:%' OR CONVERT(`description` USING utf8mb4) LIKE '%Para cada una de las siguientes preguntas, por favor marque el cuadrito con la respuesta que refleje mejor qué tan bueno es usted para realizar las siguientes cosas:%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Para cada una de las siguientes preguntas, por favor marque el cuadrito con la respuesta que refleje mejor qué tan bueno es usted para realizar las siguientes cosas:%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Para cada una de las siguientes preguntas, por favor marque el cuadrito con la respuesta que refleje mejor qué tan bueno es usted para realizar las siguientes cosas:%' OR CONVERT(`default` USING utf8mb4) LIKE '%Para cada una de las siguientes preguntas, por favor marque el cuadrito con la respuesta que refleje mejor qué tan bueno es usted para realizar las siguientes cosas:%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Para cada una de las siguientes preguntas, por favor marque el cuadrito con la respuesta que refleje mejor qué tan bueno es usted para realizar las siguientes cosas:%') AND `id` = '3059';
UPDATE `preferences_text` SET `id` = '2522', `languages_id` = '2', `title` = '', `description` = '', `instructions` = '', `placeholder` = 'Siguiente', `default` = 'Anterior', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '46', `questions_id` = NULL, `answers_id` = NULL WHERE `id` = '2522';
UPDATE `preferences_text` SET `id` = '2952', `languages_id` = '2', `title` = '', `description` = '', `instructions` = '', `placeholder` = 'Siguiente', `default` = 'Anterior', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '47', `questions_id` = NULL, `answers_id` = NULL WHERE `id` = '2952';

-- Descripcion de la colonoscopia / sigmoidoscopia / FIT
UPDATE `preferences_text` SET `id` = '1231', `languages_id` = '2', `title` = 'Información de cancer de colon y recto', `description` = '', `instructions` = '', `placeholder` = 'Terminado', `default` = 'Comenzar', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = '2', `sections_id` = NULL, `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Información de cancer de colon y recto%' OR CONVERT(`description` USING utf8mb4) LIKE '%Información de cancer de colon y recto%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Información de cancer de colon y recto%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Información de cancer de colon y recto%' OR CONVERT(`default` USING utf8mb4) LIKE '%Información de cancer de colon y recto%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Información de cancer de colon y recto%') AND `id` = '1231';

-- Description Colonoscopy / Sigmoidoscopy / FIT
UPDATE `preferences_text` SET `id` = '17', `languages_id` = '1', `title` = 'Colorectal Cancer Information', `description` = '', `instructions` = '', `placeholder` = 'Finished', `default` = 'Begin', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = '2', `sections_id` = NULL, `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%What is colorectal cancer and why is it important to get tested?%' OR CONVERT(`description` USING utf8mb4) LIKE '%What is colorectal cancer and why is it important to get tested?%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%What is colorectal cancer and why is it important to get tested?%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%What is colorectal cancer and why is it important to get tested?%' OR CONVERT(`default` USING utf8mb4) LIKE '%What is colorectal cancer and why is it important to get tested?%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%What is colorectal cancer and why is it important to get tested?%') AND `id` = '17';

-- Sigmoidoscopia / Videocolonoscopia -> Sigmoidoscopia in Preference Elicitaion
UPDATE `preferences_text` SET `id` = '2180', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Esta prueba examina el tercio inferior del colon.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '176', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2180';
UPDATE `preferences_text` SET `id` = '2550', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Si existieran 10 cánceres en la parte baja del colon, esta prueba podría detectar 9 ó 10 de ellos.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '223', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2550';
UPDATE `preferences_text` SET `id` = '2553', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'El costo promedio sin seguro médico es de : $500  a $750 \r\nDe acuerdo a la ley de Cuidado de Salud Accesible  (Affordable Care Act  en Inglés ), todos los planes de salud deben cubrir cualquier exámen preventivo, tal como la sigmoidoscopía.  Sin embargo, es posible que usted tenga que hacer un copago o  pagar un deducible.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '224', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2553';
UPDATE `preferences_text` SET `id` = '2555', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'De cada 20,000 exámenes, 1 puede resultar en una complicación grave.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '225', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2555';
UPDATE `preferences_text` SET `id` = '2557', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Es recomendable hacerse este exámen cada 5 años.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '226', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2557';
UPDATE `preferences_text` SET `id` = '2559', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Si usted se hace este exámen, podría tener  cólicos abdominales, diarrea y gases antes, durante y después del exámen.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '227', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2559';
UPDATE `preferences_text` SET `id` = '2563', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Si el resultado es anormal, usted tendría que hacerse una colonoscopía  para saber si algo está mal.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '229', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2563';
UPDATE `preferences_text` SET `id` = '2567', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Este exámen puede ser realizado por un médico general o un médico especialista en el consultorio del médico o en un hospital.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '231', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2567';
UPDATE `preferences_text` SET `id` = '2569', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Como preparación para éste exámen, usted tendrá que hacer lo siguiente: Después de la medianoche de la noche anterior al exámen, no se puede comer ni beber nada. Una hora antes de la prueba, es necesario que se ponga 2 enemas/lavativas  las cuales causan diarrea y vacían el colon. Enema es  un procedimiento para limpiar el colon que consiste en introducir líquido al colon a través del ano. El día de la prueba no debe desayunar, pero puede tomar sus medicamentos.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '232', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2569';
UPDATE `preferences_text` SET `id` = '2571', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'No requiere', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '233', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2571';
UPDATE `preferences_text` SET `id` = '2573', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Este exámen requiere aproximadamente 30 minutos. Usted necesitará tomarse medio día de sus actividades regulares.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '234', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2573';
UPDATE `preferences_text` SET `id` = '2575', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'La evidencia científica de alta calidad sugiere que esta prueba puede prevenir de 2 a 4 de cada 10 nuevos casos de cáncer. De forma similar, la evidencia científica de alta calidad sugiere  que esta prueba puede prevenir  de 3 a 5 de cada 10 muertes por cancer de colon y recto si se realiza éste examen periódicamente después de los 50 años de edad.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '235', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2575';
UPDATE `preferences_text` SET `id` = '2577', `languages_id` = '2', `title` = 'Sigmoidoscopía:', `description` = 'Cuando se decida a realizarse esta prueba, tendrá que cambiar su dieta, hacer una cita, comprar la solución para el enema y aplicárselo en casa según las instrucciones.', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = '236', `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`description` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`default` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Sigmoidoscopía / Videocolonoscopía%') AND `id` = '2577';

-- Preguntas finales
UPDATE `preferences_text` SET `id` = '3283', `languages_id` = '2', `title` = 'Escala de preparacion para la toma de decisions', `description` = '', `instructions` = 'Por favor indique su opinión sobre el efecto del material educativo seleccionado la respuesta mas apropiada para mostrar hasta qué punto está de acuerdo con cada afirmación', `placeholder` = 'Siguiente', `default` = 'Anterior', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = '68', `questions_id` = NULL, `answers_id` = NULL WHERE (CONVERT(`title` USING utf8mb4) LIKE '%el número apropiado %' OR CONVERT(`description` USING utf8mb4) LIKE '%el número apropiado %' OR CONVERT(`instructions` USING utf8mb4) LIKE '%el número apropiado %' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%el número apropiado %' OR CONVERT(`default` USING utf8mb4) LIKE '%el número apropiado %' OR CONVERT(`object_label` USING utf8mb4) LIKE '%el número apropiado %') AND `id` = '3283';

-- Hyphenate 'Extremadamente' in button labels
UPDATE `preferences_text` SET `id` = '2930', `languages_id` = '2', `title` = 'Extrema- damente', `description` = '0', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '1312' WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`description` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`default` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Extremadamente%') AND `id` = '2930';
UPDATE `preferences_text` SET `id` = '3083', `languages_id` = '2', `title` = 'Extrema- damente Bueno', `description` = '6', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '1359' WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`description` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`default` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Extremadamente%') AND `id` = '3083';
UPDATE `preferences_text` SET `id` = '3084', `languages_id` = '2', `title` = 'Extrema- damente Bueno', `description` = '6', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '1360' WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`description` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`default` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Extremadamente%') AND `id` = '3084';
UPDATE `preferences_text` SET `id` = '3096', `languages_id` = '2', `title` = 'Extrema- damente Bueno', `description` = '6', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '1366' WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`description` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`default` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Extremadamente%') AND `id` = '3096';
UPDATE `preferences_text` SET `id` = '3108', `languages_id` = '2', `title` = 'Extrema- damente Bueno', `description` = '6', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '1372' WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`description` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`default` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Extremadamente%') AND `id` = '3108';
UPDATE `preferences_text` SET `id` = '3120', `languages_id` = '2', `title` = 'Extrema- damente Bueno', `description` = '6', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '1378' WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`description` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`default` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Extremadamente%') AND `id` = '3120';
UPDATE `preferences_text` SET `id` = '3159', `languages_id` = '2', `title` = 'Extrema- damente útil', `description` = '6', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '1389' WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`description` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`default` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Extremadamente%') AND `id` = '3159';
UPDATE `preferences_text` SET `id` = '3171', `languages_id` = '2', `title` = 'Extrema- damente útil', `description` = '6', `instructions` = '', `placeholder` = '', `default` = '', `object_label` = '', `sites_id` = NULL, `projects_id` = NULL, `forms_id` = NULL, `sections_id` = NULL, `questions_id` = NULL, `answers_id` = '1395' WHERE (CONVERT(`title` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`description` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`instructions` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`placeholder` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`default` USING utf8mb4) LIKE '%Extremadamente%' OR CONVERT(`object_label` USING utf8mb4) LIKE '%Extremadamente%') AND `id` = '3171';

--
-- Contents of 0.13.4/02-fix-spacing-in-spanish-text.sql
--
-- Fix spacing in spanish text
UPDATE `preferences_text` SET `title` = '¿Qué tan bueno es usted para calcular cuánto costará una camisa si tiene un 25% de descuento?', WHERE `id` = '3071'and `languages_id` = '2';
UPDATE `preferences_text` SET `title` = '¿Lo prepare para sus visitas de seguimiento con su doctor?' WHERE `id` = '3919' and `languages_id` = '2';
UPDATE `preferences_text` SET `title` = 'Rehusa / No sé' WHERE `title` = 'Rehusa/No sé' and `languages_id` = '2';

--
-- Contents of 0.13.4/99_bump_version_number.sql
--
update forms set version='0.13.4' where 1=1;

