INSERT INTO `preferences_text` (`id`, `languages_id`, `title`, `description`, `instructions`, `placeholder`, `default`, `object_label`, `sites_id`, `projects_id`, `forms_id`, `sections_id`, `questions_id`, `answers_id`) VALUES
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1279),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1280),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1281),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1282),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1283),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1284),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1285),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1286),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1287),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1288),
(NULL,	2,	'Sí',	'0',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1289),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1290),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1301),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1291),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1302),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1292),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1303),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1293),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1304),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1294),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1305),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1295),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1306),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1296),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1307),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1297),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1308),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1298),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1309),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1299),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1310),
(NULL,	2,	'No sé',	'2',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1300),
(NULL,	2,	'No',	'4',	'',	'',	'',	'',	NULL,	NULL,	NULL,	NULL,	NULL,	1311);
